Answer question
neonoxd/trashbot pull request #13
Opened 2022-04-20 20:19 UTC by hmarcell

2022-04-20 21:30 UTC, neonoxd requested changes

2022-04-20 21:30 UTC, neonoxd commented on cogs/impl/shitpost.py
> +	await cog.bot.change_presence(activity=discord.Game(
csak akkor changeljen presencet ha proccolt különben minden üzire váltana activityt

2022-04-25 19:54 UTC, hmarcell commented on cogs/impl/shitpost.py
> +	await cog.bot.change_presence(activity=discord.Game(
ű

2022-04-25 22:51 UTC, neonoxd approved these changes

2022-04-25 22:51 UTC, merged